export function concat(...objects: object[]): object;
export function all_entries(object: object): Entries;
export function modify(object: object, modifier: ModifyCallback): object;
export function forEach(object: object, foreach: ForEach): object;
export function map(object: object, mapper: Mapper): object;
export function filter(object: object, filterer: Filter): object;
export function sort(object: object, sorter: Sort, buckets?: number | any[] | undefined): object[];
export function view(object: object, ignore_list?: string[]): object;
export function view_prototype(type: class, output?: any[]): Record<Key, Function>;
export function init<T extends class>(target: object, type: new () => T, ...args: any[]): T;
export function verify<T extends class>(target: object, type?: (new () => T) | undefined): object;
export function build<T extends class>(target: object, ...args: any[]): T;
export function construct<T extends class>(target: object, ...args: any[]): T;
declare const Object: ObjectConstructor;
export default Object;
export type Key = string | symbol;
export type KeyValuePair = [Key, any];
export type Entries = KeyValuePair[];
export type ModifyCallback = (entries: Entries) => Entries;
export type ForEach = (key: Key, value: any) => void;
export type Mapper = (key: Key, value: any) => KeyValuePair;
export type Filter = (key: Key, value: any) => boolean;
export type Sort = (key: Key, value: any) => number;
