#!/usr/bin/env bash

# CREATE BUILD FILES
bun i
rm -rf ./out/
echo "Transpiling TypeScript -> out/"
./node_modules/typescript/bin/tsc

# REINSTALL MODULE
cd ../
echo "Reinstall Plugin -> node_modules/gem-lsp/"
rm -rf node_modules/gem-lsp
bun i

echo "Done."
